import re
import json

def _robust_parse_json(raw: str) -> dict:
    """[SOVEREIGN PARSER]: Robustly extracts JSON from LLM output, handling markdown and artifacts."""
    clean = raw.strip()
    if clean.startswith("```json"): clean = clean[7:]
    elif clean.startswith("```"): clean = clean[3:]
    if clean.endswith("```"): clean = clean[:-3]
    clean = clean.strip()
    
    try:
        return json.loads(clean)
    except Exception:
        # aggressive mitigation for trailing commas before brackets generated by weak LLMs
        clean_no_comma = re.sub(r',\s*([\]}])', r'\1', clean)
        try:
            return json.loads(clean_no_comma)
        except Exception as e:
            raise ValueError(f"Directorial Parsing Failure: {str(e)}")

def _build_prompt(text: str, persona: str, user_chapters: list[dict] = None) -> tuple[str, bool]:
    """[DIRECTORIAL INSTRUCTIONS]: The high-fidelity expert prompts for the Industrial Pipeline."""
    
    if persona == "Developmental Editor":
        # Branched Pacing Intelligence:
        if not user_chapters or len(user_chapters) == 0:
            branch_instruction = """
            [MANUSCRIPT HAS NO EXISTING STRUCTURE - BLANK STATE] 
            You ARE the first architect. Identify natural narrative pauses and suggest a FULL, balanced Chapter structure from scratch.
            """
        else:
            chap_summary = "\n".join([f"- Chapter {c.get('chapter_number', i+1)}: '{c.get('suggested_title', 'Untitled')}'" for i, c in enumerate(user_chapters)])
            branch_instruction = f"""
            [DISRUPTIVE NARRATIVE AUDIT - EXISTING STRUCTURE DETECTED] 
            Current Chapter Pacing: {chap_summary}
            DIAGNOSTIC TASK: Identify all chapters exceeding 20 minutes as 'Rhythm Violations.'
            ARCHITECTURAL TASK: You are NOT bound by the author's current chapter breaks. If a chapter is too long, suggest new breaks.
            """

        prompt = f"""
        You are an elite Disruptive Narrative Architect. 
        {branch_instruction}
        
        CRITICAL FORMATTING: Use standard straight apostrophes (') and straight double quotes (") exclusively.
        MANDATORY METADATA: For EVERY chapter, provide:
        1. 'emotional_intensity' (1-10).
        2. 'suggested_title': A compelling, professional title.
        3. 'reasoning': Brief explanation of the break's effectiveness.
        4. 'starting_words': EXACTLY 10 to 15 unique, consecutive words of the paragraph where this chapter begins.
        
        Format the output as a strict JSON object:
        {{
          "chapters": [
            {{
                "chapter_number": 1, 
                "suggested_title": "...", 
                "emotional_intensity": 5,
                "reasoning": "...", 
                "starting_words": "..."
            }}
          ]
        }}
        Manuscript Text:
        {text[:50000]}
        """
        return prompt, True

    elif persona == "Copy Editor":
        prompt = f"""
        You are a Master Copy Editor. Audit the following prose for grammar, style, and narrative flow.
        Focus on Ron's specific authorial DNA: rhythmic sentence length, vocabulary complexity, and sensory immersion.
        
        Format the output as JSON:
        {{
            "feedback": "markdown report...",
            "edits": [
                {{ "original": "...", "suggestion": "...", "reason": "..." }}
            ]
        }}
        Text:
        {text[:20000]}
        """
        return prompt, True

    elif persona == "Marketing Executive":
        prompt = f"""
        You are a Publishing Marketing Executive. Generate pitch hooks, audience demographics, and a back-cover blurb.
        Format as JSON:
        {{
            "feedback": "markdown report...",
            "suggestions": [
                {{ "id": "m-1", "type": "insert", "label": "Add Blurb", "content": "...", "reason": "..." }}
            ]
        }}
        Text: {text[:20000]}
        """
        return prompt, True

    elif persona == "Sensitivity Reader":
        prompt = f"""
        You are a Sensitivity Reader. Analyze the text for cultural nuances, potential trigger warnings, and problematic tropes.
        Format as JSON:
        {{
            "feedback": "markdown...",
            "suggestions": []
        }}
        Text: {text[:30000]}
        """
        return prompt, True

    else:
        prompt = f"""
        You are a specialist in {persona}. Audit the following text for professional narrative fidelity.
        Format as JSON: {{ "feedback": "markdown...", "suggestions": [] }}
        Text: {text[:15000]}
        """
        return prompt, True
